
[project]
name = "ble-wifi-connector"
version = "0.1.0"
description = "JOI BLE WiFi Connector"
authors = [{ name = "MySmaX", email = "mysmaxlab@gmail.com" }]
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
  "termcolor",
  "getmac",
  "typing-extensions>=4.0",
  "dataclasses; python_version<'3.7'",
  "pytest",
  "pytest-timeout",
  "pytest-asyncio",
  "importlib-metadata",
  "bless==0.2.6",
  "bleak==0.22.3",
  "dbus-next",
  "uvloop",
  "zeroconf",
  "click",
]

[project.scripts]
ble-wifi-connector = "ble_wifi_connector.ble_advertiser:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["ble_wifi_connector*"]
# exclude = ["log*"]
